image:
- Visual Studio 2017
- Visual Studio 2019
- Ubuntu

install:
- ps: |
    Install-Module -Name Pester -Force -SkipPublisherCheck

build:
  off

test_script:
- pwsh: |
    . ./ci.ps1

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    test_script:
      - ps: |
          . ./ci.ps1